import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="font-inter">
                <div className="flex h-screen">
                    {/* <!-- Сайдбар с отступом слева и фиксированной позицией --> */}
                    <div className="fixed w-56 h-full overflow-y-auto pl-8">
                        <Sidebar />
                    </div>

                    {/* <!-- Контентная область с отступом для сайдбара и хедером --> */}
                    <div className="flex-1 flex flex-col pl-56">
                        {/* <!-- Хедер прибит к верху --> */}
                        <header className="bg-white p-4">
                            <Header />
                        </header>

                        {/* <!-- Основной контент по центру --> */}
                        <main className="flex-1 p-4">{children}</main>
                    </div>
                </div>
            </body>
        </html>
    );
}